#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : compat-libvpx-soname5
Version  : 1.7.0
Release  : 1
URL      : https://github.com/webmproject/libvpx/archive/v1.7.0.tar.gz
Source0  : https://github.com/webmproject/libvpx/archive/v1.7.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause HPND
Requires: compat-libvpx-soname5-bin = %{version}-%{release}
Requires: compat-libvpx-soname5-lib = %{version}-%{release}
Requires: compat-libvpx-soname5-license = %{version}-%{release}
BuildRequires : nasm
BuildRequires : yasm
Patch1: build.patch

%description
Android.mk will build vpx unittests on android.
1) Configure libvpx from the parent directory:
./libvpx/configure --target=armv7-android-gcc --enable-external-build \
--enable-postproc --disable-install-srcs --enable-multi-res-encoding \
--enable-temporal-denoising --disable-unit-tests --disable-install-docs \
--disable-examples --disable-runtime-cpu-detect --sdk-path=$NDK

%package bin
Summary: bin components for the compat-libvpx-soname5 package.
Group: Binaries
Requires: compat-libvpx-soname5-license = %{version}-%{release}

%description bin
bin components for the compat-libvpx-soname5 package.


%package dev
Summary: dev components for the compat-libvpx-soname5 package.
Group: Development
Requires: compat-libvpx-soname5-lib = %{version}-%{release}
Requires: compat-libvpx-soname5-bin = %{version}-%{release}
Provides: compat-libvpx-soname5-devel = %{version}-%{release}

%description dev
dev components for the compat-libvpx-soname5 package.


%package lib
Summary: lib components for the compat-libvpx-soname5 package.
Group: Libraries
Requires: compat-libvpx-soname5-license = %{version}-%{release}

%description lib
lib components for the compat-libvpx-soname5 package.


%package license
Summary: license components for the compat-libvpx-soname5 package.
Group: Default

%description license
license components for the compat-libvpx-soname5 package.


%prep
%setup -q -n libvpx-1.7.0
%patch1 -p1
pushd ..
cp -a libvpx-1.7.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1549385736
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export FCFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export FFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export CXXFLAGS="$CXXFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
%configure --disable-static || : ; CC=gcc CXX=g++ AR=ar STRIP=strip NM=nm ./configure --prefix=/usr --libdir=/usr/lib64 --target=x86_64-linux-gnu --disable-static --enable-libs --enable-vp8 --enable-vp9 --enable-runtime-cpu-detect --enable-shared --enable-webm-io --enable-experimental
make  %{?_smp_mflags} V=1 AS_FLAGS="-a AMD64"

unset PKG_CONFIG_PATH
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=haswell"
export CXXFLAGS="$CXXFLAGS -m64 -march=haswell"
export LDFLAGS="$LDFLAGS -m64 -march=haswell"
%configure --disable-static || : ; CC=gcc CXX=g++ AR=ar STRIP=strip NM=nm ./configure --prefix=/usr --libdir=/usr/lib64 --target=x86_64-linux-gnu --disable-static --enable-libs --enable-vp8 --enable-vp9 --enable-runtime-cpu-detect --enable-shared --enable-webm-io --enable-experimental
make  %{?_smp_mflags} V=1 AS_FLAGS="-a AMD64"
popd
%install
export SOURCE_DATE_EPOCH=1549385736
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/compat-libvpx-soname5
cp LICENSE %{buildroot}/usr/share/package-licenses/compat-libvpx-soname5/LICENSE
cp third_party/googletest/src/LICENSE %{buildroot}/usr/share/package-licenses/compat-libvpx-soname5/third_party_googletest_src_LICENSE
cp third_party/libwebm/LICENSE.TXT %{buildroot}/usr/share/package-licenses/compat-libvpx-soname5/third_party_libwebm_LICENSE.TXT
cp third_party/x86inc/LICENSE %{buildroot}/usr/share/package-licenses/compat-libvpx-soname5/third_party_x86inc_LICENSE
pushd ../buildavx2/
%make_install_avx2
popd
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
%exclude /usr/bin/haswell/vpxdec
%exclude /usr/bin/haswell/vpxenc
%exclude /usr/bin/vpxdec
%exclude /usr/bin/vpxenc

%files dev
%defattr(-,root,root,-)
%exclude /usr/include/vpx/vp8.h
%exclude /usr/include/vpx/vp8cx.h
%exclude /usr/include/vpx/vp8dx.h
%exclude /usr/include/vpx/vpx_codec.h
%exclude /usr/include/vpx/vpx_decoder.h
%exclude /usr/include/vpx/vpx_encoder.h
%exclude /usr/include/vpx/vpx_frame_buffer.h
%exclude /usr/include/vpx/vpx_image.h
%exclude /usr/include/vpx/vpx_integer.h
%exclude /usr/lib64/haswell/libvpx.so
%exclude /usr/lib64/libvpx.so
%exclude /usr/lib64/pkgconfig/vpx.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/haswell/libvpx.so.5
/usr/lib64/haswell/libvpx.so.5.0
/usr/lib64/haswell/libvpx.so.5.0.0
/usr/lib64/libvpx.so.5
/usr/lib64/libvpx.so.5.0
/usr/lib64/libvpx.so.5.0.0

%files license
%defattr(0644,root,root,0755)
%exclude /usr/share/package-licenses/compat-libvpx-soname5/LICENSE
%exclude /usr/share/package-licenses/compat-libvpx-soname5/third_party_googletest_src_LICENSE
%exclude /usr/share/package-licenses/compat-libvpx-soname5/third_party_libwebm_LICENSE.TXT
%exclude /usr/share/package-licenses/compat-libvpx-soname5/third_party_x86inc_LICENSE
